name: time_series_forecasting
channels:
  - defaults
  - conda-forge
  - pytorch
  - plotly
  - nvidia
dependencies:
  - python=3.12
  - numpy
  - pandas
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - yfinance
  - plotly
